import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Container, Flex, Box, Heading } from '@chakra-ui/react';
import { Nav } from '../components/nav';
import { Main } from '../components/main';
import { teamInfo } from '../contstants';
import { Card } from '../components/card';
import { ScoreTable } from '../components/scoretable';
import { useGetScore } from '../hooks/fetchData';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { score } = useGetScore();

  const redTeamScore = score?.filter((item) => item.team === 'red-team').reduce((acc, item) => acc + item.value, 0);

  const blueTeamScore = score?.filter((item) => item.team === 'blue-team').reduce((acc, item) => acc + item.value, 0);

  const redTeamTableData = score?.filter((item) => item.team === 'red-team').map(({ value, reason }) => ({ value, reason }));

  const blueTeamTableData = score?.filter((item) => item.team === 'blue-team').map(({ value, reason }) => ({ value, reason }));


  return (
    <>
      <Head>
        <title>Encounter Score</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Nav />
        <Container maxW="container.xl" h="100%">
          <Flex
            mt={20}
            flexWrap="wrap"
            justifyContent="space-around"
            alignItems="start"
          >
            <Box mb={[20, 20, 20, 0]}>
              <Heading
                as="h2"
                fontSize={{
                  sm: 'xl',
                  md: '2xl',
                  lg: '5xl',
                  base: 'xl'
                }}
                color={teamInfo.red.color}
                mb={4}
              >
                {teamInfo.red.teamName}
              </Heading>
              <Card team="red" mb={4}>
                {redTeamScore}
              </Card>
              <ScoreTable data={redTeamTableData} />
            </Box>
            <Box>
              <Heading
                as="h2"
                fontSize={{
                  sm: 'xl',
                  md: '2xl',
                  lg: '5xl',
                  base: 'xl'
                }}
                color={teamInfo.blue.color}
                mb={4}
              >
                {teamInfo.blue.teamName}
              </Heading>
              <Card team="blue" mb={4}>
                {blueTeamScore}
              </Card>
              <ScoreTable data={blueTeamTableData} />
            </Box>
          </Flex>
        </Container>
      </Main>
    </>
  );
}
